### ISSUE TITLE
Attachment of Deployment Artifacts

### ISSUE THREAD

**Issue by mbeisel** [SeQuenC-Consortium/workflow-modeler#1]
## Problem Statement

It shall be possible to attach a docker image reference and source files (e.g., zip containing python files, requirements, ...) as a Deployment Artifact.
The attachment shall exclusively be possible for Service-Tasks. It shall be available when selecting 'Deployment Model' in the 'Implementation' tab. Users shall either select an existing CSAR OR upload a Deployment Artifact (which is used to generate a service template).

## Issue Dependencies

Depends on:  #2 

## Sketch
![grafik](https://github.com/SeQuenC-Consortium/workflow-modeler/assets/19931367/4fcb7fe9-0da2-4fd8-b91e-a0258b3006b8)

## References

Documentation included in WF Modeler.

## Tasks

- [x] Add deployment property to the properties panel, when an activity is selected
- [x] Add a file dialog where users can upload their deployment files
- [x] Retrieve the file as a blob for later transmission to [Winery](https://github.com/OpenTOSCA/winery)

**Comment by ArneBartenbach** [comment]
alte Story Points 10

**Comment by mbeisel** [comment]
updated task description

**Comment by PatrickEbner** [comment]
Alte Story Points: 8
