### ISSUE TITLE
Creation of Deployment Plugin

### ISSUE THREAD

**Issue by mbeisel** [SeQuenC-Consortium/workflow-modeler#2]
## Problem Statement

All functionality regarding the deployment of services, containers, etc. shall be handled by a separate deployment plugin within the workflow modeler.

Currently, the QuantME plugin contains functionalities for the [deployment of services](https://github.com/SeQuenC-Consortium/workflow-modeler/tree/master/components/bpmn-q/modeler-component/extensions/quantme/deployment). These shall be transferred into a [new deployment plugin](https://github.com/SeQuenC-Consortium/workflow-modeler/blob/master/doc/quantum-workflow-modeler/editor/plugin/create-new-plugin.md).

## Setup Prerequisite
- Setup workflow modeler
- Setup OpenTOSCA: https://github.com/OpenTOSCA/opentosca-docker/blob/main/docs/tutorial-model-and-deploy.md 

## References
[Quantum Workflows](https://ieeexplore.ieee.org/abstract/document/9302814) 
[Self-Contained WF Models](http://www2.informatik.uni-stuttgart.de/cgi-bin/NCSTRL/NCSTRL_view.pl?id=INPROC-2020-15)

## Tasks

- [x] Create the deployment plugin
- [x] Transfer all deployment functionalities from the QuantME plugin into the deployment plugin
- [x] Enable the activation of the plugin via the Docker setup (#6)
- [x] Test the functionality utilizing the use case described in #7 
- [x] Derive and implement suitable test cases based on this use case

**Comment by ArneBartenbach** [comment]
alte Story Points 8
