### ISSUE TITLE
Visualize On-Demand Deployment

### ISSUE THREAD

**Issue by wiomoc** [SeQuenC-Consortium/workflow-modeler#24]
## Problem Statement

The transformed Workflows should be visualized in camunda cockpit

## Issue Dependencies

Depends on: 
https://github.com/SeQuenC-Consortium/workflow-modeler/issues/3

## Tasks
- [x] Add a [view](https://link.springer.com/content/pdf/10.1007/s42979-022-01625-9.pdf) visualizing the initially modeled workflow instead of the executed one, i.e., showing the service tasks instead of the subprocesses for on-demand deployed services:
  - [x] Use the example view available [here](https://github.com/UST-QuAntiL/camunda-process-views-plugin) as a baseline 
  - [x] Mark subprocesses related to on-demand deployment during transformation within the modeler (e.g., add a certain XML attribute)
  - [x] Within the view plugin, analyze the current workflow model and depending on the selected view (modeled workflow; with deployment information), visualize the subprocesses or the service tasks

**Comment by KuhnMn** [comment]
Split up from #4

**Comment by wiomoc** [comment]
Testing depends on #4
