### ISSUE TITLE
Environment Variable for Qunicorn

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/workflow-modeler#37]
**Problem Statement:**

Qunicorn is a stable component, so there should be already an environment variable with the default port.

**Expected Behavior:**
Should be in the list of configurations.

**Tasks:**

- [ ] Define the environment variable
- [ ] Add a new entry in the config UI
- [ ] Test the environment variable in a workflow
