### ISSUE TITLE
Qunicorn Task for the workflow-modeler

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/workflow-modeler#38]
**Problem Statement:**
At the moment, Qunicorn is reached via Service Tasks with REST-calls implemented in a groovie script.

**References (Optional):**

The Custom Task can be implemented similar to the other custom tasks in the QuantME: https://github.com/UST-QuAntiL/QuantME-TransformationFramework

**Expected Behavior:**

The custom task should do a service call and use the environment variable implemented here #37 .
It should have fields for the REST-Method and the payload, as well as output variables for the response.

**Tasks:**

- [ ] Implement the UI-Element of the Quncorn Task, using the qunicorn image
- [ ] Add fields for the aforementioned parameters
- [ ] Test the custom task in a workflow
- [ ] Create an example workflow in the SeQuenC Use-Cases
- [ ] Dokument the features / usage of the task
