### ISSUE TITLE
Enable On-Demand Deployment Transformation

### ISSUE THREAD

**Issue by mbeisel** [SeQuenC-Consortium/workflow-modeler#4]
## Problem Statement

In addition to the available pre-execution service deployment, it shall be possible to deploy services on-demand, i.e., a service is deployed right before the task requiring the service is executed.

## Issue Dependencies

Depends on: 
https://github.com/SeQuenC-Consortium/workflow-modeler/issues/3

## Tasks

- [x] When clicking on the ``Deploy Workflow`` button it should be checked if there are still attached deployment models within the workflow:
  - [x] Deploy the workflow if no deployment models are attached
  - [x] Open a pop-up otherwise enabling to directly deploy the workflow or decide for on-demand deployment
  - [x] In case of on-demand deployment, transform the workflow as described below 
- [x] Transform the workflow to support the on-demand deployment of required services:
  - [x] Add a subprocess instead of the service task
  - [x] Add two service tasks within the subprocess: The first should deploy the required service using OpenTOSCA, and the second should perform the service invocation defined by the modeled service task
  - [x] Transform service tasks with a `deploymentUrl` into a form that a unmodified camunda engine accepts.
  - [x] Add Metadata to the Model specifying the opentosca url, the buildplan url and the instance url of deployed tasks

## References

[On-Demand Deployment](https://ieeexplore.ieee.org/document/6717290)

**Comment by KuhnMn** [comment]
Split up from _Enable On-Demand Deployment_

**Comment by PatrickEbner** [comment]
Old estimate: 13
