### ISSUE TITLE
Deployment Monitoring

### ISSUE THREAD

**Issue by mbeisel** [SeQuenC-Consortium/workflow-modeler#5]
---

## Problem Statement

During runtime the status of all deployments shall be shown in a "Deployment View" in the workflow engine user interface.
Thus, the user interface shall be extended by a dedicated deployment view in the process overview, which displays all crucial information about all deployments.

## Issue Dependencies

Depends on: 
https://github.com/SeQuenC-Consortium/workflow-modeler/issues/3 

## References

[Views in Workflows](https://link.springer.com/content/pdf/10.1007/s42979-022-01625-9.pdf)
[Views in Workflows Use Case](https://github.com/UST-QuAntiL/QuantME-UseCases/tree/master/2022-sncs)
[Example implementation of views for Camunda 7](https://github.com/UST-QuAntiL/camunda-process-views-plugin)

## Tasks

- [ ] Receive deployment information from OpenTOSCA
- [ ] Conceptualize the layout of the view component and select attributes to be displayed
- [ ] Display deployment information in a dedicated deployment view.

---

**Comment by wiomoc** [comment]
Testing depends on #4
