### ISSUE TITLE
Dockerize Workflow Modeler

### ISSUE THREAD

**Issue by wederbn** [SeQuenC-Consortium/workflow-modeler#6]
## Problem Statement

Dockerize the quantum workflow modeler by providing a corresponding Dockerfile as well as automating the creation of images through GitHub workflows.
Enable the adaptation of the modeler configuration via environment variables, e.g., which [plugins](https://github.com/SeQuenC-Consortium/workflow-modeler/blob/master/doc/quantum-workflow-modeler/editor/plugin/plugin-integration.md) should be loaded on startup.

## Tasks

- [x] Update [Dockerfile](https://github.com/SeQuenC-Consortium/workflow-modeler/blob/master/Dockerfile) to use npm production mode instead of development mode.
- [x] Use a multi-step build to decrease image size (see [here](https://docs.docker.com/build/building/multi-stage/))
- [x] Add a GitHub workflow to automatically push an image to the [PlanQK organization](https://hub.docker.com/u/planqk) on Dockerhub (i) when committing to the master branch (tag: latest) and (ii) when creating a new release (reuse release number as tag name). Use the secrets available within this repository (see [here](https://github.com/UST-QuAntiL/Quokka/blob/main/.github/workflows/dockerhub.yml#L31))
- [x] Add configuration via environment variables.

**Comment by wiomoc** [comment]
* Image is pushed to internal repository for now, because Dockerhub is used for the main repo.

**Comment by BonnetGa** [comment]
Confluence Seite "Docker" bitte erweitern

**Comment by wiomoc** [comment]
> Confluence Seite "Docker" bitte erweitern

Done

**Comment by BonnetGa** [comment]
Doku für Config Variablen und diese Testen
