### ISSUE TITLE
Visualize Deployment Model within Workflow Modeler

### ISSUE THREAD

**Issue by mbeisel** [SeQuenC-Consortium/workflow-modeler#9]
## Problem Statement

To visualize the deployment model attached to activities, the deployment graph shall be shown within the workflow modeler.

## Issue Dependencies

Depends on: #3 

## Expected Behaviour

There should be a button on activities that contain a deployment model.
Users shall be able to toggle the visualization of the deployment graph by clicking the deployment model icon.
Moreover, the deployment model shall be clearly distinguished from activities of the workflow (see below):

![grafik](https://github.com/SeQuenC-Consortium/workflow-modeler/assets/19931367/7f0e76b7-d283-405d-8539-06a7152bcd27)

## Tasks

- [x] Use the given [icon](https://github.com/SeQuenC-Consortium/workflow-modeler/assets/19931367/4b13b07b-433a-4269-a11a-6323e5f85f57) to mark tasks containing a deployment model URL 
- [x] Retrieve ServiceTemplate content from deployment model URL
- [x] Visualize the deployment model as follows:
    - [x] The visualization shall be toggled when clicking on the deployment model icon
    - [x] The top node of the deployment model containing the uploaded artifact is represented by the activity
       - [x] To identify the the top level node [TOSCA Tags](http://docs.oasis-open.org/tosca/TOSCA/v1.0/os/TOSCA-v1.0-os.html#_Toc356403659) shall be used (key: "top-node"; value: "NODE_XYZ"). 
       - [ ] When building a ServiceTemplate via uploading an artifact, the tag shall be set automatically to the node containing the uploaded deployment artifact.
       - [x] When using an existing Service Template, it shall be checked if the "top-node" tag is available. If the tag is not available it shall be checked if a top-node can be identified (_if exactly one without incoming hosted-on_ should suffice). If no top-node can be identified, the topology will not be shown.
    - [x] All other nodes of the deployment model shall be shown below the activity as depicted above
    - [x] The layout of the deployment model shall be derived from the visualization in the Winery. Use the coordinates given in the ServiceTemplate response
    - [x] A new modeling element representing deployment topology nodes shall be added. The style of above figure shall be used
    - [x] A new arrow type for connecting deployment nodes shall be added. The style of above figure shall be used
    - [x] The options enabling users to change the type or delete a node shall be deactivated for all deployment nodes
    - [ ] #10

**Comment by mbeisel** [comment]
added more detailed description for displaying the deployment models top node
